In [3]:
import numpy as ny

In [4]:
#criando uma matriz
matriz1 = ny.array([[1,2,3],[4,5,6]])
print(matriz1)

[[1 2 3]
 [4 5 6]]


In [5]:
print(matriz1.shape)

(2, 3)


In [6]:
#criando uma matriz 2x3 apenas com numeros 1
matriz2 = ny.ones((2,3))
print(matriz2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#lista de lista
lista = [[13,81,22],[0,34,59],[21,48,94]]
arr = ny.matrix(lista)
print(arr)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [8]:
#indexção duas dimensões 

arr[2,1]#primeiro coluna e depois linha

48

In [9]:
#range de linhas 
arr[0:2,2]

matrix([[22],
        [59]])

In [10]:
# intervalo da coluna 1, ou seja, coluna 1 e todos seus elementos 
arr[1,]

matrix([[ 0, 34, 59]])

In [12]:
#alterando um elemento da matriza 
arr [1,0]=100
print(arr)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [13]:
#fazendo tipagem 
x = ny.array([1,2]) #numpy decide o tipo de dados
y = ny.array([1.0,2.0]) #numpy decide o tipo de dados
z = ny.array([1,2],dtype = ny.float64) # Forçãmos um tipo de dado em particular 

print(x,y,z)

[1 2] [1. 2.] [1. 2.]


In [15]:
# itemsize de um array numpy é o tamanho em bytes de cada elemento array

arr.itemsize

4

In [16]:
arr.nbytes #numero de bytes

36

In [17]:
arr.ndim

2