In [3]:
import numpy as nupy

arrl =nupy.array([10,21,34,56,78,91,67])
print(arrl)

[10 21 34 56 78 91 67]


In [3]:
type(arrl)

numpy.ndarray

In [4]:
#verificando o formato do array
arrl.shape

(7,)

In [3]:
#imprimindo um elemento especifico do array 

arrl[4]

78

In [5]:
arrl[0:4]

array([10, 21, 34, 56])

In [6]:
#lista de indices

indices = [1,2,4,5]

In [7]:
#imprimendo os elementos do array com as posicões selecionadas na lista 
arrl[indices]

array([21, 34, 78, 91, 67])

In [10]:
#criando uma mascara boleana para numeros pares 
mask =(arrl % 2 == 0 )
arrl[mask]

array([10, 34, 56, 78])

In [11]:
#alterando elemento no array

arrl[0]=100
print(arrl)

[100  21  34  56  78  91  67]


In [ ]:
#não é possivel inserir um elemento de type diferente!!

In [4]:
#FUNÇÃO NUMPYYYY

arr2 = nupy.array([1,2,3,4,5,9])
print(arr2)

[1 2 3 4 5 9]


In [13]:
#metodo para soma acumulada

arr2.cumsum()

array([ 1,  3,  6, 10, 15, 24], dtype=int32)

In [5]:
#produto acumulado
arr2.cumprod()

array([   1,    2,    6,   24,  120, 1080], dtype=int32)

In [6]:
#A função ARANGE cria um array numpy contendo uma prograssão aritimética a partir de um intervalo- star,stop,step
arr3 = nupy.arange(0,50,5)

In [7]:
arr3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
#formato do array
nupy.shape(arr3)

(10,)

In [23]:
#redimensionado um array 
a = nupy.arange(6).reshape((3,2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [13]:
#cria um array preenchido por zeros
arr4 = nupy.zeros(10)

In [11]:
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
#cria um array preenchido por um's
b = nupy.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [26]:
#cria um array com valores aleatorios
random_array = nupy.random.random((5))
print(random_array)

[0.13858392 0.27978624 0.97164211 0.07571876 0.52278292]


In [15]:
#a função eye retona 1 nas diagonais e 0 nas restantes 
arr5 = nupy.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#criando uma matriz com números aleatorios 
d = nupy.floor(10*nupy.random.random((3,4)))#o parametro significa 3 linhas e 4 elementos em cada linha
print(d)

[[8. 4. 6. 4.]
 [2. 7. 5. 3.]
 [6. 2. 9. 3.]]


In [16]:
#criando uma matriz com valores de um array
arr6 = nupy.diag(nupy.array([1,2,3,4]))
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
#array com valores booleanos
arr7 = nupy.array([True,False,False,True])
print(arr7)

[ True False False  True]


In [20]:
#array de strings

arr8 = nupy.array(['Python','R','Julia'])
print(arr8)

['Python' 'R' 'Julia']


In [21]:
#FUNÇÃO LINSPACE()
#é usada para criar uma serquencia de números igualmente espaçados dentro de um intervalo especifico. É uma funçao
#amplamente usada em programação cientifica e matematica para gerar arrays de números para devidos fins, como graficos,
#calculos e simulções.
#O metodo linspace() RETORNA um numero de valores igualmente distribuidos no intervalo especifico 

print(nupy.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [22]:
#FUNÇÃO LOGSPACE()
#é usada para criar uma sequencia de números igualmente espaçados em escala logaritma dentro de um intervalo especifico
#essa função é amplamente usada para gerar arrays de numeros para diversos fins como graficos, calculos e simulações.

print(nupy.logspace(0,5,10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]
