In [1]:
import numpy as ny

arr15 = ny.arange(1,10)
print(arr15)

[1 2 3 4 5 6 7 8 9]


In [2]:
#soma dos elementos do array
ny.sum(arr15)

45

In [3]:
#produto dos elementos 
ny.prod(arr15)

362880

In [4]:
#soam acumulada dos elementos 
ny.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [5]:
#criar dois arrays
arr16 = ny.array([3,2,1])
arr17 = ny.array([1,2,3])

In [6]:
#soma dos dois arrays
arr18 = ny.add(arr16,arr17)
print(arr18)

[4 4 4]


MULTIPLICAÇÃO DE MATRIZES!!!! ATENCIONNNNNNNNN

In [7]:
#criando duas matrizes 

matriz_1 = ny.array([[1,2],[4,4]])
matriz_2 = ny.array([[5,6],[0,7]])

In [8]:
matriz_1.shape

(2, 2)

In [9]:
matriz_2.shape

(2, 2)

In [10]:
#multiplicação de matrizes 
#para multiplicar duas matrizes podemos usar a função dot() ou @.MUITO IMPORTANTE LEMBRAR que para a multiplicação
#de matrizes acontecer o número de linhas e de colunas deve ser IGUAL

matriz_mult = ny.dot(matriz_1,matriz_2)#a ordem dos arrays importa por conta da regra de o numero de colunas e linhas serem =
print(matriz_mult)

[[ 5 20]
 [20 52]]


SLICING(FATIAMENTO)

In [12]:
a = ny.array([1,2,3,4])
b = ny.array([4,2,2,4])


In [13]:
#comparação de item a intem

a == b

array([False,  True, False,  True])

In [14]:
#comparação global

ny.array_equal(a,b)

False

In [15]:
#valor minimo 
b.min()

2

In [16]:
#valor maximo
a.max()

4

In [18]:
#somando um valor a cada elemento do array

c = ny.array([1,2,3,5,6,7])+2
print(c)

[3 4 5 7 8 9]


In [19]:
matriz_5 = ny.array([[1,2,3,4],[5,6,7,8]])
print(matriz_5)

[[1 2 3 4]
 [5 6 7 8]]


O metodo flatten() com numpy é usado para criar uma copia unidimensional ou achatada da matriz. Isso quer dizer que o método cria um novo array unidimensional, que contém todos os elementos do array original mas que estará organizado em uma unica linha.A nova ordem segue a ordem do array antigo

In [21]:
achat = matriz_5.flatten()
print(achat)

[1 2 3 4 5 6 7 8]


In [22]:
g = ny.array([1,2,3])

In [23]:
#repetindo elementos do array
ny.repeat(g,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [24]:
#repetindo os elementos do array 
ny.tile(g, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])